@startuml
!theme hacker
title "org orgzly" flow

folder org {
	stack org_files
}
folder orgzly {
	stack orgzly_files
}
folder tmp1 {
	stack tmp1_files
}
folder tmp2 {
	stack tmp2_files
}

hexagon org_parse
hexagon duplicate_check

cloud Dropbox {
	folder remote_orgzly {
		stack dropbox_files
			}
}

org_files --> duplicate_check : "(1) '--push' to orgzly"
duplicate_check --> loz : "(2) dedupe"
dropbox_files --> tmp1_files
tmp_oz_files --> dupe
dupe --> doz
parse --> loz : "(1B) '--push' to orgzly"
loz --|> doz : "(2) '--put' in Dropbox"
doz --|> dupe : "(3A) '--get' from Dropbox"
dupe --> loz : "(3B) '--get' from Dropbox"
@enduml
